[2021-09-06 14:35:48] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/config/routes/dev/framework.yaml {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/appdata/www/vendor/symfony/config/Resource/FileResource.php\",\"line\":62,\"trace\":[{\"file\":\"/appdata/www/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2021-09-06 14:35:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:35:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:250/")" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:250/\") at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:35:48] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/config/routes/dev/framework.yaml {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/appdata/www/vendor/symfony/config/Resource/FileResource.php\",\"line\":62,\"trace\":[{\"file\":\"/appdata/www/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2021-09-06 14:35:48] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:35:48] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:250/\") at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:35:48] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:250/\") at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:35:48] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:35:48] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:250/\") at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:48:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:48:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:48:27] request.INFO: Matched route "standar". {"route":"standar","route_parameters":{"_route":"standar","_controller":"App\\Controller\\StandarController::index"},"request_uri":"http://localhost:250/index.php/standar","method":"GET"} []
[2021-09-06 14:48:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-09-06 14:48:27] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:48:27] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:48:27] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:48:27] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:48:28] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:48:28] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:48:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:50:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:51:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:51:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:51:24] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:51:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:51:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:53:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:53:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /public/index.php"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /public/index.php\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/public/index.php/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:06] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:53:06] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /public/index.php\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/public/index.php/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /public/index.php\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/public/index.php/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:06] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:53:06] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /public/index.php\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/public/index.php/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:11] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-09-06 14:53:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index.html.twig"" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html.twig\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index.html.twig/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:34] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:53:34] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html.twig\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index.html.twig/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:34] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html.twig\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index.html.twig/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-06 14:53:34] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102) {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-09-06 14:53:34] php.CRITICAL: Uncaught Exception: An exception occurred in driver: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /appdata/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html.twig\" at /appdata/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index.html.twig/\". at /appdata/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.en.xlf {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/administrador/public_html/Symfony-Project/vendor/symfony/config/Resource/FileResource.php\",\"line\":62,\"trace\":[{\"file\":\"/home/administrador/public_html/Symfony-Project/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.af.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.ar.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.az.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.be.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.bg.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.bs.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.ca.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.cs.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.cy.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.da.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.de.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.el.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.es.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.et.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.eu.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.fa.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.fi.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.fr.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.gl.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.he.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.hr.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.hu.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.hy.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.id.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.it.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.ja.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.lb.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.lt.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.lv.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.mn.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.nb.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.nl.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.nn.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.no.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.pl.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.pt.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.pt_BR.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.ro.xlf [] []
[2021-09-07 08:46:12] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.ru.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.sk.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.sl.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.sq.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.sr_Cyrl.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.sr_Latn.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.sv.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.th.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.tl.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.tr.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.uk.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.uz.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.vi.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.zh_CN.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/project-symfony/vendor/symfony/validator/Resources/translations/validators.zh_TW.xlf [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/config/routes/dev/framework.yaml [] []
[2021-09-07 08:46:13] php.DEBUG: Warning: filemtime(): stat failed for /appdata/www/config/routes/dev/framework.yaml [] []
